monolog:
  handlers:
    file_log:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      max_files: 10

    syslog_handler:
      type: syslog
      level: error